package io.github.jixingdefeng.visionrealm.common.particle;

import com.google.common.cache.Cache;
import com.google.common.cache.CacheBuilder;
import com.google.gson.JsonParser;
import com.mojang.serialization.Codec;
import com.mojang.serialization.JsonOps;
import com.mojang.serialization.MapCodec;
import io.github.jixingdefeng.visionrealm.api.event.particle.RegistryParticleConfigTypeEvent;
import io.github.jixingdefeng.visionrealm.api.particle.ParticleConfig;
import io.github.jixingdefeng.visionrealm.common.util.hash.FingerprintUtil;
import io.github.jixingdefeng.visionrealm.common.util.particle.ParticleTemplates;
import io.github.jixingdefeng.visionrealm.core.VisionRealm;
import io.github.jixingdefeng.visionrealm.impl.particle.EmptyParticleConfig;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.packs.resources.Resource;
import net.minecraft.server.packs.resources.ResourceManager;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.event.server.ServerStartingEvent;
import net.neoforged.neoforge.event.server.ServerStoppingEvent;
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;

/**
 * Loads and caches particle configurations from data packs.
 * <p>
 * This class provides a registry for reusable particle configurations. By extracting
 * common particle effects into separate JSON files, configurations can be referenced
 * by ID rather than being duplicated across multiple erosion key definitions.
 * </p>
 * <p>
 * The {@code type} field in the JSON file determines which particle configuration
 * implementation to use.
 * </p>
 *
 * <p><b>File Location:</b></p>
 * <pre>
 * data/&lt;namespace&gt;/particle_configs/&lt;id&gt;.json
 * </pre>
 *
 * <p><b>JSON Structure Example:</b></p>
 * <pre>
 * {
 *   "type": "visionrealm:singleton",
 *   "particle": {
 *     "type": "minecraft:campfire_cosy_smoke",
 *     "data": {}
 *   }
 * }
 * </pre>
 *
 * @author JiXingDeFeng
 * @see ParticleConfig
 * @since 0.0.1-dev
 */
public class ParticleConfigLoader {
    public static final String PATH = "particle_configs";
    private static final Cache<ResourceLocation, ParticleConfig> TEMP_CACHE = CacheBuilder.newBuilder()
            .maximumSize(500)
            .expireAfterAccess(10, TimeUnit.MINUTES)
            .build();
    private static final Map<ResourceLocation, ParticleConfig> PERSISTENT_STORAGE = new ConcurrentHashMap<>();
    private static final Map<ResourceLocation, MapCodec<? extends ParticleConfig>> CODECS = new ConcurrentHashMap<>();
    private static ResourceManager resourceManager;

    /**
     * Checks whether a persistent particle configuration exists for the given location.
     * <p>
     * The location can be either:
     * <ul>
     *   <li>A standard resource location (e.g., "minecraft:some_particle_config")</li>
     *   <li>An inline identifier composed of a hash value and internal cache marker</li>
     * </ul>
     * </p>
     *
     * @param location The resource location key
     * @return {@code true} if a configuration exists, {@code false} otherwise
     */
    public static boolean containsKey(ResourceLocation location) {
        return PERSISTENT_STORAGE.containsKey(location);
    }

    /**
     * Checks whether a codec is registered for the specified particle configuration type.
     *
     * @param location The type identifier (e.g., "visionrealm:singleton")
     * @return {@code true} if a codec is registered, {@code false} otherwise
     */
    public static boolean containsCodec(ResourceLocation location) {
        return CODECS.containsKey(location);
    }

    /**
     * Retrieves the codec for the specified particle configuration type.
     *
     * @param type The type identifier (e.g., "visionrealm:singleton")
     * @return The codec for this type, or {@link EmptyParticleConfig#MAP_CODEC} if not registered
     */
    public static MapCodec<? extends ParticleConfig> getCodec(ResourceLocation type) {
        return CODECS.getOrDefault(type, EmptyParticleConfig.MAP_CODEC);
    }

    /**
     * Caches a particle configuration using a generated key based on its type and content.
     * <p>
     * The key is generated by hashing the type identifier and the configuration content,
     * then combining with {@link VisionRealm#INLINE_DATA_ID} as a marker.
     * </p>
     *
     * @param particle The particle configuration to cache
     * @param codec    The codec used to encode/decode the particle
     * @param <T>      The specific particle configuration type
     * @return The generated resource location key
     */
    public static <T extends ParticleConfig> ResourceLocation cachePersistent(T particle, Codec<T> codec) {
        ResourceLocation key = ResourceLocation.fromNamespaceAndPath(
                FingerprintUtil.hashString(ResourceLocation.CODEC, particle.getType()),
                VisionRealm.INLINE_DATA_ID + FingerprintUtil.hashString(codec, particle)
        );
        return cachePersistent(key, particle);
    }

    /**
     * Caches a particle configuration with the specified key.
     *
     * @param location The resource location key
     * @param config   The particle configuration to cache
     * @return The resource location key, or {@code null} if the config is a placeholder
     */
    public static ResourceLocation cachePersistent(ResourceLocation location, ParticleConfig config) {
        if (config instanceof EmptyParticleConfig) {
            return null;
        }

        PERSISTENT_STORAGE.put(location, config);
        return location;
    }

    @Nullable
    public static ParticleConfig load(ResourceLocation id) {
        return load(id, false, false);
    }

    /**
     * Loads a particle configuration from the specified resource location.
     * <p>
     * This method looks for a JSON file at:
     * <pre>data/&lt;namespace&gt;/particle_configs/&lt;path&gt;.json</pre>
     * </p>
     *
     * @param id          The resource location ID of the particle configuration
     * @param persistent  Whether to store permanently (true = persistent storage, false = temporary cache)
     * @param forceReread Whether to ignore cache and force reload from disk
     * @return The loaded particle configuration, or {@link ParticleTemplates#empty()} if loading failed
     */
    @Nullable
    public static ParticleConfig load(ResourceLocation id, boolean persistent, boolean forceReread) {
        if (id == null) return null;

        if (!forceReread) {
            if (PERSISTENT_STORAGE.containsKey(id)) {
                return PERSISTENT_STORAGE.get(id);
            }

            ParticleConfig particleConfig = TEMP_CACHE.getIfPresent(id);
            if (particleConfig != null) {
                return particleConfig;
            }
        }

        if (resourceManager == null) {
            VisionRealm.LOGGER.warn("Cannot load particle config: resourceManager is null");
            return ParticleTemplates.empty();
        }

        ResourceLocation location = ResourceLocation.fromNamespaceAndPath(id.getNamespace(), PATH + "/" + id.getPath() + ".json");
        Optional<Resource> resource = resourceManager.getResource(location);

        try (var reader = resource.orElseThrow(() -> new NoSuchElementException("Resource not found: " + location)).openAsReader()) {
            ParticleConfig config = ParticleConfig.CODEC.parse(JsonOps.INSTANCE, JsonParser.parseReader(reader))
                    .result()
                    .orElseThrow(() -> new NoSuchElementException("Failed to load particle config at " + location));
            if (config instanceof EmptyParticleConfig) {
                if (location.getPath().startsWith(VisionRealm.INLINE_DATA_ID)) {
                    VisionRealm.LOGGER.warn(
                            "Inline particle config with hash {} resolved to EmptyParticleConfig (fallback). Please check the inline particle definition.",
                            location
                    );
                } else {
                    VisionRealm.LOGGER.warn(
                            "Particle config at {} resolved to EmptyParticleConfig (fallback). This may indicate a missing or invalid particle definition. If no particle effect is intended, omit the 'particle' field entirely.",
                            location
                    );
                }

                return null;
            } else {
                if (persistent) {
                    cachePersistent(id, config);
                } else {
                    TEMP_CACHE.put(id, config);
                }

                return config;
            }
        } catch (IOException e) {
            VisionRealm.LOGGER.error("Failed to load particle config at {}", location, e);
        }

        return null;
    }

    /**
     * Initializes the particle config manager by collecting registered particle config types.
     * <p>Posts a {@link RegistryParticleConfigTypeEvent} to collect all registered
     * particle configuration codecs, enabling dynamic dispatch based on the type field.</p>
     *
     * @param bus The mod event bus
     */
    @ApiStatus.Internal
    public static void initialize(IEventBus bus) {
        RegistryParticleConfigTypeEvent event = new RegistryParticleConfigTypeEvent();
        bus.post(event);
        CODECS.putAll(event.getParticles());
    }

    /**
     * Handles server startup to initialize the resource manager.
     * <p>Also clears the temporary cache to free memory.</p>
     *
     * @param event The server starting event
     */
    @ApiStatus.Internal
    public static void start(ServerStartingEvent event) {
        TEMP_CACHE.cleanUp();
        resourceManager = event.getServer().getResourceManager();
    }

    /**
     * Handles server stopping to clean up resources.
     * <p>Clears persistent storage and releases the resource manager reference.</p>
     *
     * @param event The server stopping event
     */
    @ApiStatus.Internal
    public static void close(ServerStoppingEvent event) {
        PERSISTENT_STORAGE.clear();
        resourceManager = null;
    }

    private ParticleConfigLoader() {
    }
}
